
include(YCMEPHelper)

include(FindOrBuildPackage)

ycm_ep_helper(CARLsimGUI TYPE GIT 
    STYLE GITHUB
    REPOSITORY UCI-CARL/CARLsimGUI.git
    #TAG master
    TAG feat/raspi5
    COMPONENT SNN
    FOLDER src
    DEPENDS QT5 CARLsimIO
    CMAKE_ARGS 
      -DCARLSIMGUI_USES_CARLSIM:BOOL=${CARLSIMPP_USES_CARLSIM}
      -DCARLSIMGUI_USES_CARLSIMIO:BOOL=${CARLSIMPP_USES_YARP}        # fix Linux Pi 5   
      -DCARLSIMGUI_CARLSIM_NO_CUDA=${CARLSIMPP_USES_CUDA}           # new Linux Pi 5         
      -DCARLSIMGUI_ENABLE_DEPRECATED:BOOL=FALSE)    
