
include(YCMEPHelper)

include(FindOrBuildPackage)

ycm_ep_helper(CARLsimGUI TYPE GIT 
    STYLE GITHUB
    REPOSITORY UCI-CARL/CARLsimGUI.git
    #TAG master
    COMPONENT SNN
    FOLDER src
    DEPENDS QT5 CARLsimIO
    CMAKE_ARGS 
      -DCARLSIMGUI_USES_CARLSIM:BOOL=${CARLSIMPP_USES_CARLSIM}
      -DCARLSIMGUI_USES_CARLSIMIO:BOOL=${CARLSIMPP_ENABLE_GPU}                            
      -DCARLSIMGUI_ENABLE_DEPRECATED:BOOL=FALSE)    