
if(CARLSIMPP_USES_YARP)
	find_package(Eigen3 3.3.9 HINTS ${CMAKE_BINARY_DIR}/share/eigen3/cmake)  
	if(NOT Eigen3_FOUND)
		find_or_build_package(Eigen3)
	endif()
	find_package(YARP 3.4.6 HINTS ${CMAKE_BINARY_DIR}/share/yarp/cmake)  
	if(NOT YARP_FOUND)
		find_or_build_package(YARP)
	endif()
endif()

if(CARLSIMPP_ENABLE_SNN)
	if(CARLSIMPP_USES_CUDA)
		find_or_build_package(CudaSamples)
	endif()
	if(CARLSIMPP_ENABLE_EDGE)
		find_or_build_package(GTest)
	endif()
	find_or_build_package(CARLsim6)
endif()

if(CARLSIMPP_ENABLE_CORE)
	if(CARLSIMPP_USES_YARP)
		find_or_build_package(CARLcpp)
		find_or_build_package(YarpLibCarl)
		if(CARLSIMPP_ENABLE_EDGE)
			#find_or_build_package(YarpDevCarlWb)    # Webots does not support aarch64
			find_or_build_package(YarpDevCarlEpuck2)
		endif()
		find_or_build_package(CARLsimIO)
	endif()
	find_or_build_package(Service)
endif()

if(CARLSIMPP_ENABLE_SNN)
	if(CARLSIMPP_USES_QT)
		find_or_build_package(CARLsimGUI)
	endif()
endif()
